name: soulfyre
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  provider: ^6.0.4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/future.svg
    - assets/images/past.svg
    - assets/images/present.svg

fonts:
  - family: EncodeSans
    fonts:
      - asset: assets/fonts/EncodeSans-Black.ttf
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Regular.ttf
        weight: 400
      - asset: assets/fonts/Lato-Light.ttf
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 800
