name: orangelist
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

# - name: Due Dates
#   uses: alexleventer/github-issue-due-dates-action@1.1.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.2
  feedback: ^3.1.0
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^7.0.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  provider: ^6.1.2
  shared_preferences: ^2.0.17
  universal_io: ^2.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^2.0.0
  hive_test: ^1.0.1
  mocktail: ^1.0.4
  change_app_package_name: ^1.3.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/app_icon.png"
    background_color: "0d0d0d"
    theme_color: "f55e3a"

flutter_native_splash:
  color_dark: "#0d0d0d"
  color: "#0d0d0d"
  image: "assets/logo/app_icon.png"
  android: true
  ios: true
  web: true

  android_12:
    color: "#0d0d0d"


flutter:
  uses-material-design: true

  assets:
    - assets/images/happy.svg
    - assets/images/monthlyOverview.svg
    - assets/images/dragAndOrder.svg
    - assets/svgs/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500

    - family: LibreBaskerville
      fonts:
        - asset: assets/fonts/LibreBaskerville-Bold.ttf
          weight: 700

    - family: Majoris
      fonts:
        - asset: assets/fonts/Majoris.ttf
          weight: 700
