name: CI
on:
  push:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'adopt'

      # Set up Flutter and run test
      - uses: subosito/flutter-action@v2
        with:
          # Update this once the project flutter version is updated
          flutter-version: '3.22.0'
      - run: flutter pub get
      - run: echo "KEY=VALUE" > .env # Creating a mock .env file
      - run: flutter analyze --no-fatal-warnings
      - run: flutter test

  # On Test Success version bump or else flow fails
  bump_version:
    name: Bump version 
    needs: [flutter_test]
    runs-on: ubuntu-latest
    outputs:
      version_bumped: ${{ steps.version_bump.outcome == 'success' && steps.version_bump.outputs.new_tag != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          DEFAULT_BUMP: patch # patch means: from `v1.0.0` to `v1.0.1`. 
          # There's *major* for `v2.0.0` and *minor* for `v1.0.0` to `v1.1.0`
          WITH_V: true # for 'v' as prefix for versions like - `v1.0.0`

# Here we will only do the CI, so just testing and version bump.
