name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'adopt'

      # Set up Flutter and run test
      - uses: subosito/flutter-action@v2
        with:
          # Update this once the project flutter version is updated
          flutter-version: '3.22.0'
      - run: flutter pub get
      - run: echo "KEY=VALUE" > .env # Creating a mock .env file
      - run: flutter analyze --no-fatal-warnings
      - run: flutter test

  # On Test Success version bump or else flow fails
  bump_version:
    name: Bump version 
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          DEFAULT_BUMP: patch # patch means: from `v1.0.0` to `v1.0.1`. 
          # There's *major* for `v2.0.0` and *minor* for `v1.0.0` to `v1.1.0`
          WITH_V: true # for 'v' as prefix for versions like - `v1.0.0`

  # Build app bundle
  build_appbundle:
    name: Build Flutter (Android)
    needs: [bump_version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'adopt'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - run: flutter clean
      - run: flutter pub get
      - run: echo "KEY=VALUE" > .env # Creating a mock .env file
      - run: flutter build appbundle

  build_web:
    name: Build Flutter (web)
    needs: [bump_version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'adopt'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - run: flutter clean
      - run: flutter pub get
      - run: echo "KEY=VALUE" > .env # Creating a mock .env file
      - run: flutter build web --release

  # Revert version bump if build fails
  revert_version_bump:
    name: Revert Version Bump
    needs: [build_appbundle, build_web]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          DEFAULT_BUMP: none # This will undo the version bump by resetting the tag
          WITH_V: true # To revert to correct format

  push_artifacts:
    name: Push to Releases
    needs: [build_appbundle, build_web]
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/app-release.aab,build/web"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.ACTIONS_TOKEN }}

# Here since we are not deploying directly to the playstore we can call it delivery and not deployment
